### ISSUE TITLE
lester laptop coords

### ISSUE THREAD

**Issue by Imnotryanofficial** [Mo1810/mo_lifeinvaderRobbery#1]
Hi i have a problem about lester laptop coord when player go outside its still visible.

![Screenshot (2254)](https://user-images.githubusercontent.com/73257079/112898333-48664480-9113-11eb-90bb-a27948488ec7.png)

**Comment by Mo1810** [comment]
Thank you for your feedback!
The bug should be fixed now.

**Comment by Mo1810** [comment]
@
