### ISSUE TITLE
Spam message error with extended

### ISSUE THREAD

**Issue by JeDebute01** [Mo1810/mo_lifeinvaderRobbery#2]
Everythink it's in this image ;) i have the version 1.2.0 of extended

![Capture d’écran 2021-06-07 215336](https://user-images.githubusercontent.com/18090946/121079830-f3157600-c7da-11eb-9f2f-21e875e0def9.png)

**Comment by Mo1810** [comment]
Ok, should be fixed now. I changed the name of the script and then forgot to change the name of the events in the server sided script. You can now pull the new _lifeinvaderHeist-s.lua_ file. Thank you for reporting!
