### ISSUE TITLE
Void LifeInvader

### ISSUE THREAD

**Issue by ThePurpleRats** [Mo1810/mo_lifeinvaderRobbery#3]
@Mo1810 you have a bug like when you try to enter side you fall in the void
![void](https://user-images.githubusercontent.com/117203295/201194381-ae6cc546-a82e-4459-8932-f91bdddc29af.PNG)

**Comment by Mo1810** [comment]
Hey @ThePurpleRats ,
thanks for reporting the bug. I tried replicating the bug but wasn't able to. 
Could you try describing the circumstances closer where you entered what? 
Thanks in advance!
